#
# Makefile for PicoTCP as Linux TCP/IP replacement.
#
ccflags-y += -I net/picotcp/include -I net/picotcp/modules -I net/tcpip

obj-y     := af_inet.o \
			netdev.o \
			sock.o \
			ioctl.o \
			proc.o \
			core.o

